name: Build and Push Docker image to DockerHub
on: [push,workflow_dispatch]
jobs:
  Build-Push:
     runs-on: ubuntu-latest
     steps:
       - name: Check out the repo 
         uses: actions/checkout@v3

       - name: Login to DockerHub
         uses: docker/login-action@v3 
         with: 
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}